### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by lillux** [raphael-group/GASTON#2]
Hi, I had some issue with the installation of `gaston` (pip install -e .).
I SOLVED by:
- removing `pyproject.toml`,
- adding a `,` (comma) at the end of line 21 of `setup.py` (after `scikit-learn` requirement).

**Comment by uthsavc** [comment]
Thank you for debugging! That is annoying that I was missing a comma in `setup.py` -- I just added it. Hopefully this fixes the issue.
