### ISSUE TITLE
Handling low-quality cells

### ISSUE THREAD

**Issue by simonmfr** [raphael-group/GASTON#6]
GASTON recognizes low-quality cells (with few reads) as a separate domain. Should these cells be excluded before running GASTON, or is it important to include them in the raw data analysis? Thanks!

**Comment by uthsavc** [comment]
I would suggest removing these cells. Leaving this open for now: I'll add some pre-processing code to the tutorial for removing cells with UMI count < some threshold.

**Comment by simonmfr** [comment]
Great, thanks.

**Comment by uthsavc** [comment]
I updated the Visium/Slide-Seq tutorials (colorectal tumor and cerebellum, respectively) to expose a minimum UMI threshold.
