### ISSUE TITLE
pytorch installation in env.yaml without gpu support

### ISSUE THREAD

**Issue by OliiverHu** [raphael-group/GASTON#8]
Hi! 

Thanks for sharing this fantastic project. I encountered this problem during env configuration. It seems that following the tutorial does have everything set up smoothly. However, during training, I noticed that the torch is actually installed with the cpu version? (.cuda.is_available() = False). I am not sure what might cause the problem. I tried to uninstall torch and then re-install with a explictly stated gpu version but failed since the dependencies are incompatible.

<img width="782" alt="image" src="https://github.com/user-attachments/assets/2244e71f-386a-41f9-8fd3-911eeccc5258">

Still working on it and we appreciate any insights you could provide!

Thanks!

**Comment by uthsavc** [comment]
Sorry for my delay in response - thanks for your interest in our work! 

Currently GASTON training is only done using CPU which is why Pytorch is installed with CPU. But we have a GPU version of GASTON currently in development. (It should be ready soon, I just need to perform some beta-testing)

**Comment by OliiverHu** [comment]
Thanks! I hope everything goes well with your beta-testing.

And again, this work is super cool and I did use the cpu version to validate the effectiveness of our method. Thanks for coming up with the lovely idea :)

Regards,
