### ISSUE TITLE
No `tissue_positions_list` in Google Drive for tutorial

### ISSUE THREAD

**Issue by wwang-chcn** [raphael-group/GASTON#9]
I'm trying to following the tutorial of **Continuous gradients in colorectal tumor**. However, I failed to found the `spatial/tissue_positions_list.csv` file in the Google Drive. Could you please upload it?

**Comment by uthsavc** [comment]
Sorry that is a typo in the notebook. The file is located here: https://github.com/raphael-group/GASTON/tree/main/docs/notebooks/tutorials/colorectal_tumor_data/spatial
